FROM python:3.9

# 必要なシステムライブラリをインストール
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender1

WORKDIR /app
COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000
ENV PATH $PATH:/app
CMD ["flask", "run", "--host=0.0.0.0"]
