FROM python:3.9

WORKDIR /app
COPY requirements.txt .

# RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000
ENV PATH $PATH:/app
CMD ["flask", "run", "--host=0.0.0.0"]
