version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - your_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - your_network

networks:
  your_network:
