version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
